

# Site Settings
locale                   : "en-US"
title                    : "the_widening_gyre"
title_separator          : "|"
name                     : &name "Bradley Gibbs" # &name is a YAML anchor which can be *referenced later
description              : &description "A curated collection for the discerning data scientist."
url                      : https://thegyre.io 
baseurl                  :  # the subpath of your site, e.g. "/blog"
repository               : 
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman_v2", "staticman" "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : # "New comment"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "_data/comments/{options.slug}"
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"


# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/bradley-gibbs.jpg"
  bio              : "still figuring it out."
  location         : "Austin, TX"
  email            :
  uri              : "https://thegyre.io"
  home             : "https://thegyre.io"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : 
  foursquare       :
  github           : "dbfreq"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : 
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : #
  steam            :
  tumblr           :
  twitter          : *twitter
  vine             :
  weibo            :
  xing             :
  youtube          :


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  coursework:
    output: true
    permalink: /:collection/:path/
  notes:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /:collection/:path/



# Defaults
defaults:
# _coursework
  - scope:
      path: "_coursework"
      type: coursework
    values:
      layout: notebooks
      author_profile: false
      share: true
      toc: true
      sidebar: coursework
  # _notes
  - scope:
      path: "_notes"
      type: notes
    values:
      layout: notebooks
      author_profile: false
      toc: true
      sidebar: notes
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: default
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true




# Sass/SCSS
sass:
  sass_dir: css
  

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
#  - jemoji



# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
